name: Docker Image

on:
  workflow_dispatch:
 
env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_SRC: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: set lower case repo name 
        run: |
          echo IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: get dockerfile version
        run: |
          echo IMAGE_VERSION=$(cat $IMAGE_SRC/Dockerfile | grep "LABEL version" | awk -F '"' '{print $2}') >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_ID }}
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}},value=v${{ env.IMAGE_VERSION }}
            type=ref,event=branch
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_SRC }}
          platforms: |-
              linux/amd64
              linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
